<?php

namespace Neoan3\Component\FirstComponent;

use Neoan3\Core\Unicore;

/**
 * Class FirstComponentController
 * @package Neoan3\Component\FirstComponent
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class FirstComponentController extends Unicore{
    /**
     * Route: FirstComponent
     */
    function init(): void
    {
        $this
            ->uni('Demo')
            ->hook('main', 'firstComponent')
            ->output();
    }

}